### ISSUE TITLE
Handle errors on controller level, implement logging

### ISSUE THREAD

**Issue by Gudmon** [GergelyKamaras/Filc#101]
- [x]  Add and configure logging
- [ ]  Create custom error objects
- [x]  Add try/catches to controllers
- [ ]  Handle these errors on the frontend or log them
- [ ] Add functionality to student, teacher and parent controllers as well

**Comment by Gudmon** [comment]
Error handling when trying to fetch datas that are not in the database.

**Comment by GergelyKamaras** [comment]
Partially implemented, remaining tasks moved to new card
